spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret:
    key: 62935295578DF3F31BC0467A339CDC0F351E436E50D73C93C5102A4ED0CCAE7C